### PR TITLE
Update textview at activity_main.xml

### PR DESCRIPTION
**Pull request by dimasnoufal**
Update textview at activity_main.xml

### CODE REVIEW

**Review by rosease — COMMENTED** [review]
it's me hiii

**Review by rosease — APPROVED** [review]
HOHOOO

**Review by FiqihArdiansyah — COMMENTED** [review]
No

**Review by rosease — CHANGES_REQUESTED** [review]
haloooo

**Review by FiqihArdiansyah — APPROVED** [review]
Ok

**Review by rosease — APPROVED** [review]

**Pull request merged**
